[workspace]
members = [
    "uniswap-v2/contracts/**",
    "farming/contracts/**",
    "farming/mocks/*",
    "nft/contracts/shiden34",
]

exclude = [
    "uniswap-v2/logics",
    "farming/logics",
]
